# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: skia_gold_client
publish_to: none
environment:
  sdk: '>=3.2.0-0 <4.0.0'

# Do not add any dependencies that require more than what is provided in
# $dart_src/pkg, $dart_src/third_party/pkg, or
# //third_party/pkg. In particular, package:test is not usable here.

# If you do add packages here, make sure you can run `pub get --offline`, and
# check the .packages and .package_config to make sure all the paths are
# relative to this directory into $dart_src, or //third_party/pkg
dependencies:
  crypto: any
  path: any
  engine_repo_tools: any
  process: any

dependency_overrides:
  collection:
    path: ../../../flutter/third_party/dart/third_party/pkg/collection
  crypto:
    path: ../../../flutter/third_party/dart/third_party/pkg/crypto
  engine_repo_tools:
    path: ../../tools/pkg/engine_repo_tools
  file:
    path: ../../../flutter/third_party/dart/third_party/pkg/file/packages/file
  meta:
    path: ../../../flutter/third_party/dart/pkg/meta
  path:
    path: ../../../flutter/third_party/dart/third_party/pkg/path
  platform:
    path: ../../third_party/pkg/platform
  process:
    path: ../../third_party/pkg/process
  typed_data:
    path: ../../../flutter/third_party/dart/third_party/pkg/typed_data
