# Describes the targets run in continuous integration environment.
#
# Flutter infra uses this file to generate a checklist of tasks to be performed
# for every commit.
#
# More information at:
#  * https://github.com/flutter/cocoon/blob/master/CI_YAML.md
enabled_branches:
  - master
  - dev
  - beta
  - stable
  - fuchsia_f5

platform_properties:
  linux:
    properties:
      caches: >-
        [
          {"name":"builder_linux_engine","path":"builder"},
          {"name":"openjdk","path":"java"}
        ]
      dependencies: >-
        [
          {"dependency": "open_jdk", "version": "1.8.0u202-b08"}
        ]
      os: Linux
  mac:
    properties:
      caches: >-
        [
          {"name":"flutter_cocoapods","path":"cocoapods"},
          {"name":"old_osx_sdk","path":"osx_sdk"},
          {"name":"builder_mac_engine","path":"builder"},
          {"name":"openjdk","path":"java"}
        ]
      dependencies: >-
        [
          {"dependency": "open_jdk", "version": "1.8.0u202-b08"}
        ]
      os: Mac-10.15
      xcode: 12a7209 # xcode 12
  windows:
    properties:
      caches: >-
        [
          {"name":"builder_win_engine","path":"builder"},
          {"name":"openjdk","path":"java"}
        ]
      dependencies: >-
        [
          {"dependency": "open_jdk", "version": "1.8.0u202-b08"}
        ]
      os: Windows-10

targets:
  - name: Linux Fuchsia
    builder: Linux Fuchsia
    recipe: engine
    properties:
      add_recipes_cq: "true"
      build_fuchsia: "true"
      fuchsia_ctl_version: version:0.0.27
    timeout: 90
    scheduler: luci

  - name: Linux Fuchsia FEMU
    builder: Linux Fuchsia FEMU
    recipe: femu_test
    properties:
      add_recipes_cq: "true"
      build_fuchsia: "true"
      fuchsia_ctl_version: version:0.0.27
    timeout: 60
    scheduler: luci
