gcp_credentials: ENCRYPTED[987a78af29b91ce8489594c9ab3fec21845bbe5ba68294b8f6def3cf0d380830f06687a89ea69c87344c5ade369700fe]

# LINUX
task:
  gke_container:
   image: gcr.io/flutter-cirrus/build-engine-image:latest
   cluster_name: build-32-cluster
   zone: us-central1-a
   namespace: default
   cpu: 30 # can't use all 30-cores; system pods needs cores too
   memory: 100Gb # similarly, can't use all 100Gb memory
  env:
    CIRRUS_WORKING_DIR: "/tmp/github_repo"
    ENGINE_PATH: "/tmp/clean_engine"
    DEPOT_TOOLS: "/tmp/depot_tools"
    FLUTTER_ENGINE: "/tmp/clean_engine/src"
    FRAMEWORK_PATH: "/tmp/master_framework"
    PATH: "$FLUTTER_ENGINE/third_party/dart/tools/sdks/dart-sdk/bin:$DEPOT_TOOLS:$PATH"
    USE_ANDROID: "False"
  setup_script: |
    git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git $DEPOT_TOOLS
    mkdir -p $ENGINE_PATH/src
    echo 'solutions = [{"managed": False,"name": "src/flutter","url": "git@github.com:flutter/engine.git","deps_file": "DEPS", "custom_vars": {"download_android_deps" : ' $USE_ANDROID ', "download_windows_deps" : False,},},]' > $ENGINE_PATH/.gclient
    cd $ENGINE_PATH/src
    rm -rf flutter
    rm -rf out
    mv $CIRRUS_WORKING_DIR flutter
    gclient sync
  matrix:
    - name: build_and_test_linux_unopt_debug
      compile_host_script: |
        cd $ENGINE_PATH/src
        ./flutter/tools/gn --unoptimized --full-dart-sdk
        ninja -C out/host_debug_unopt
      test_host_script: |
        cd $ENGINE_PATH/src
        ./flutter/testing/run_tests.sh host_debug_unopt
      fetch_framework_script: |
        mkdir -p $FRAMEWORK_PATH
        cd $FRAMEWORK_PATH
        git clone https://github.com/flutter/flutter.git
      test_web_script: |
        cd $FRAMEWORK_PATH/flutter/dev/integration_tests/web
        ../../../bin/flutter config --local-engine=host_debug_unopt --no-analytics --enable-web
        ../../../bin/flutter --local-engine=host_debug_unopt build web -v
      test_framework_script: |
        cd $FRAMEWORK_PATH/flutter/packages/flutter
        ../../bin/flutter test --local-engine=host_debug_unopt
