container:
  image: cirrusci/flutter:base

build_task:
  env:
    CIRRUS_WORKING_DIR: "/tmp/github_repo"
    ENGINE_PATH: "/tmp/engine"
    PATH: $PATH:/tmp/depot_tools

  download_depot_tools_script: |
    cd /tmp
    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

  engine_cache:
    folder: $ENGINE_PATH
    fingerprint_script: cd $CIRRUS_WORKING_DIR && git fetch origin master && git rev-parse FETCH_HEAD
    populate_script: |
      mkdir --parents $ENGINE_PATH && cd $ENGINE_PATH
      cp $CIRRUS_WORKING_DIR/travis/gclient .gclient
      gclient sync

  replace_engine_script: |
    cd $ENGINE_PATH/src
    rm -r flutter
    cp $CIRRUS_WORKING_DIR -r ./flutter
    gclient sync

  install_script: |
    cd $ENGINE_PATH/src
    sudo ./build/install-build-deps-android.sh
    sudo ./build/install-build-deps.sh

  compile_host_script: |
    cd $ENGINE_PATH/src
    ./flutter/tools/gn --unoptimized
    ninja -C out/android_debug_unopt

