container:
  image: cirrusci/flutter:base

build_task:
  env:
    CIRRUS_WORKING_DIR: "/tmp/engine"
    PATH: $PATH:/tmp/depot_tools

  download_depot_tools_script: |
    cd /tmp
    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

  gclient_sync_engine_script: |
    cd /tmp
    cat <<EOF > .gclient
    solutions = [
      {
        "managed": False,
        "name": "src/flutter",
        "url": "https://github.com/flutter/engine.git",
        "custom_deps": {},
        "deps_file": "DEPS",
        "safesync_url": "",
      },
    ]
    EOF
    gclient sync

  replace_engine_script: |
    cd /tmp/src
    rm -r flutter
    mv /tmp/engine ./flutter
    cd ..
    gclient sync

  compile_host_script: |
    cd /tmp/src
    ./flutter/tools/gn --unoptimized
    ninja -C out/android_debug_unopt

