name: web_sdk_tests

# Keep the SDK version range in sync with lib/web_ui/pubspec.yaml
environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  args: 2.3.1
  path: any # see dependency_overrides

dev_dependencies:
  # Using the bundled analyzer (see dependency_overrides) to always be
  # up-to-date instead of a version from pub, which may not have the latest
  # language features enabled.
  analyzer: any
  test: 1.24.8

dependency_overrides: # Must include all transitive dependencies from the "any" packages above.
  _fe_analyzer_shared:
    path: ../../flutter/third_party/dart/pkg/_fe_analyzer_shared
  analyzer:
    path: ../../flutter/third_party/dart/pkg/analyzer
  async:
    path: ../../flutter/third_party/dart/third_party/pkg/async
  collection:
    path: ../../flutter/third_party/dart/third_party/pkg/collection
  convert:
    path: ../../flutter/third_party/dart/third_party/pkg/convert
  crypto:
    path: ../../flutter/third_party/dart/third_party/pkg/crypto
  dart_internal:
    path: ../../flutter/third_party/dart/pkg/dart_internal
  file:
    path: ../../flutter/third_party/dart/third_party/pkg/file/packages/file
  glob:
    path: ../../flutter/third_party/dart/third_party/pkg/glob
  meta:
    path: ../../flutter/third_party/dart/pkg/meta
  package_config:
    path: ../../flutter/third_party/dart/third_party/pkg/package_config
  path:
    path: ../../flutter/third_party/dart/third_party/pkg/path
  pub_semver:
    path: ../../flutter/third_party/dart/third_party/pkg/pub_semver
  source_span:
    path: ../../flutter/third_party/dart/third_party/pkg/source_span
  string_scanner:
    path: ../../flutter/third_party/dart/third_party/pkg/string_scanner
  term_glyph:
    path: ../../flutter/third_party/dart/third_party/pkg/term_glyph
  typed_data:
    path: ../../flutter/third_party/dart/third_party/pkg/typed_data
  watcher:
    path: ../../flutter/third_party/dart/third_party/pkg/watcher
  yaml:
    path: ../../flutter/third_party/dart/third_party/pkg/yaml
