name: frontend_server
version: 0.1.1-dev
description: Communication pipe to Dart Frontend
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  args: any
  async: any
  charcode: any
  collection: any
  convert: any
  crypto: any
  front_end:
    path: ../../third_party/dart/pkg/front_end
  kernel:
    path: ../../third_party/dart/pkg/kernel
  logging: any
  meta: any
  quiver: any
  package_config: any
  path: any
  source_span: any
  typed_data: any
  usage: any
  vm:
    path: ../../third_party/dart/pkg/vm