name: frontend_server
version: 0.1.1-dev
description: Communication pipe to Dart Frontend
homepage: http://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

dependencies:
  args: any
  charcode: any
  collection: any
  convert: any
  crypto: any
  front_end: any
  kernel: any
  logging: any
  meta: any
  quiver: any
  package_config: any
  path: any
  source_span: any
  typed_data: any
  usage: any

dev_dependencies:
  test: any

dependency_overrides:
  args:
    path: ../../dart/third_party/pkg/args
  charcode:
    path: ../../dart/third_party/pkg/charcode
  collection:
    path: ../../dart/third_party/pkg/collection
  convert:
    path: ../../dart/third_party/pkg/convert
  crypto:
    path: ../../dart/third_party/pkg/crypto
  front_end:
    path: ../../dart/pkg/front_end/
  kernel:
    path: ../../dart/pkg/kernel/
  logging:
    path: ../../dart/third_party/pkg/logging
  meta:
    path: ../../dart/pkg/meta
  quiver:
    path: ../../dart/third_party/pkg/quiver
  package_config:
    path: ../../dart/third_party/pkg_tested/package_config
  path:
    path: ../../dart/third_party/pkg/path
  source_span:
    path: ../../dart/third_party/pkg/source_span
  test:
    path: ../../dart/third_party/pkg/test
  typed_data:
    path: ../../dart/third_party/pkg/typed_data
  usage:
    path: ../../dart/third_party/pkg/usage
