# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: flutter_frontend_server
publish_to: none
version: 0.1.1-dev
description: Communication pipe to Dart Frontend
homepage: https://flutter.dev

# Do not add any dependencies that require more than what is provided in
# //third_party/pkg, //third_party/dart/pkg or
# //third_party/dart/third_party/pkg. In particular, package:test is not usable
# here.

# If you do add packages here, make sure you can run `pub get --offline`, and
# check the .packages and .package_config to make sure all the paths are
# relative to this directory into //third_party/dart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  args: any
  frontend_server: any
  path: any

dev_dependencies:
  litetest: any

dependency_overrides:
  _fe_analyzer_shared:
    path: ../../third_party/dart/pkg/_fe_analyzer_shared
  _js_interop_checks:
    path: ../../third_party/dart/pkg/_js_interop_checks
  args:
    path: ../../third_party/dart/third_party/pkg/args
  async_helper:
    path: ../../third_party/dart/pkg/async_helper
  build_integration:
    path: ../../third_party/dart/pkg/build_integration
  compiler:
    path: ../../third_party/dart/pkg/compiler
  dart2js_info:
    path: ../../third_party/dart/pkg/dart2js_info
  dev_compiler:
    path: ../../third_party/dart/pkg/dev_compiler
  expect:
    path: ../../third_party/dart/pkg/expect
  front_end:
    path: ../../third_party/dart/pkg/front_end
  frontend_server:
    path: ../../third_party/dart/pkg/frontend_server
  js_ast:
    path: ../../third_party/dart/pkg/js_ast
  js_runtime:
    path: ../../third_party/dart/pkg/js_runtime
  js_shared:
    path: ../../third_party/dart/pkg/js_shared
  kernel:
    path: ../../third_party/dart/pkg/kernel
  litetest:
    path: ../testing/litetest
  package_config:
    path: ../../third_party/dart/third_party/pkg_tested/package_config
  path:
    path: ../../third_party/dart/third_party/pkg/path
  smith:
    path: ../../third_party/dart/pkg/smith
  vm:
    path: ../../third_party/dart/pkg/vm
