name: compare_goldens
environment:
  sdk: '>=3.2.0-0 <4.0.0'

dev_dependencies:
  async_helper: any
  expect: any
  litetest: any
  smith: any

dependency_overrides:
  async_helper:
    path: ../../../third_party/dart/pkg/async_helper
  expect:
    path: ../../../third_party/dart/pkg/expect
  litetest:
    path: ../../testing/litetest
  smith:
    path: ../../../third_party/dart/pkg/smith
