# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: apicheck
publish_to: none

# Do not add any dependencies that require more than what is provided in
# $dart_src/pkg or $dart_src/third_party/pkg.
# In particular, package:test is not usable here.

# If you do add packages here, make sure you can run `pub get --offline`, and
# check the .packages and .package_config to make sure all the paths are
# relative to this directory into $dart_src

environment:
  sdk: '>=3.2.0-0 <4.0.0'

# Do not add any dependencies that require more than what is provided in
# //third_party/pkg, $dart_src/pkg, or
# $dart_src/third_party/pkg. In particular, package:test is not usable
# here.

# If you do add packages here, make sure you can run `pub get --offline`, and
# check the .packages and .package_config to make sure all the paths are
# relative to this directory into $dart_src

dependencies:
  analyzer: any
  _fe_analyzer_shared: any
  pub_semver: any

dev_dependencies:
  async_helper: any
  expect: any
  litetest: any
  path: any
  smith: any

dependency_overrides:
  _fe_analyzer_shared:
    path: ../../../flutter/third_party/dart/pkg/_fe_analyzer_shared
  analyzer:
    path: ../../../flutter/third_party/dart/pkg/analyzer
  async:
    path: ../../../flutter/third_party/dart/third_party/pkg/async
  async_helper:
    path: ../../../flutter/third_party/dart/pkg/async_helper
  collection:
    path: ../../../flutter/third_party/dart/third_party/pkg/collection
  convert:
    path: ../../../flutter/third_party/dart/third_party/pkg/convert
  crypto:
    path: ../../../flutter/third_party/dart/third_party/pkg/crypto
  dart_internal:
    path: ../../../flutter/third_party/dart/pkg/dart_internal
  expect:
    path: ../../../flutter/third_party/dart/pkg/expect
  file:
    path: ../../../flutter/third_party/dart/third_party/pkg/file/packages/file
  glob:
    path: ../../../flutter/third_party/dart/third_party/pkg/glob
  litetest:
    path: ../../testing/litetest
  meta:
    path: ../../../flutter/third_party/dart/pkg/meta
  package_config:
    path: ../../../flutter/third_party/dart/third_party/pkg/package_config
  path:
    path: ../../../flutter/third_party/dart/third_party/pkg/path
  pub_semver:
    path: ../../../flutter/third_party/dart/third_party/pkg/pub_semver
  source_span:
    path: ../../../flutter/third_party/dart/third_party/pkg/source_span
  string_scanner:
    path: ../../../flutter/third_party/dart/third_party/pkg/string_scanner
  term_glyph:
    path: ../../../flutter/third_party/dart/third_party/pkg/term_glyph
  typed_data:
    path: ../../../flutter/third_party/dart/third_party/pkg/typed_data
  watcher:
    path: ../../../flutter/third_party/dart/third_party/pkg/watcher
  yaml:
    path: ../../../flutter/third_party/dart/third_party/pkg/yaml
  smith:
    path: ../../../flutter/third_party/dart/pkg/smith
