# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: engine_repo_tools
publish_to: none
environment:
  sdk: '>=3.2.0-0 <4.0.0'

# Do not add any dependencies that require more than what is provided in
# //third_party/pkg, $dart_src/pkg, or
# $dart_src/third_party/pkg. In particular, package:test is not usable
# here.

# If you do add packages here, make sure you can run `pub get --offline`, and
# check the .packages and .package_config to make sure all the paths are
# relative to this directory into $dart_src

dependencies:
  meta: any
  path: any

dev_dependencies:
  async_helper: any
  expect: any
  litetest: any
  smith: any

dependency_overrides:
  async_helper:
    path: ../../../../flutter/third_party/dart/pkg/async_helper
  expect:
    path: ../../../../flutter/third_party/dart/pkg/expect
  litetest:
    path: ../../../testing/litetest
  meta:
    path: ../../../../flutter/third_party/dart/pkg/meta
  path:
    path: ../../../../flutter/third_party/dart/third_party/pkg/path
  smith:
    path: ../../../../flutter/third_party/dart/pkg/smith
