name: sky_engine
version: 0.0.99
description: Dart SDK extensions for dart:ui
homepage: https://flutter.io
# sky_engine requires sdk_ext support in the analyzer which was added in 1.11.x
environment:
  sdk: '>=3.2.0-0 <4.0.0'
