name: web_test_utils

# Keep the SDK version range in sync with lib/web_ui/pubspec.yaml
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: 1.17.0
  crypto: 3.0.2
  image: 3.2.2
  js: 0.6.6
  meta: 1.8.0
  path: 1.8.3
  process: 4.2.4
  skia_gold_client:
    path: ../../testing/skia_gold_client
  typed_data: 1.3.1
  yaml: 3.1.1
