name: gen_web_keyboard_keymap
description: Generates keyboard layouts for Web from external sources.

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  args: any
  http: any
  path: any
  meta: any

dependency_overrides:
  args:
    path: ../../../flutter/third_party/dart/third_party/pkg/args
  async:
    path: ../../../flutter/third_party/dart/third_party/pkg/async
  collection:
    path: ../../../flutter/third_party/dart/third_party/pkg/collection
  http:
    path: ../../../flutter/third_party/dart/third_party/pkg/http/pkgs/http
  http_parser:
    path: ../../../flutter/third_party/dart/third_party/pkg/http_parser
  meta:
    path: ../../../flutter/third_party/dart/pkg/meta
  path:
    path: ../../../flutter/third_party/dart/third_party/pkg/path
  source_span:
    path: ../../../flutter/third_party/dart/third_party/pkg/source_span
  string_scanner:
    path: ../../../flutter/third_party/dart/third_party/pkg/string_scanner
  term_glyph:
    path: ../../../flutter/third_party/dart/third_party/pkg/term_glyph
  typed_data:
    path: ../../../flutter/third_party/dart/third_party/pkg/typed_data
